version: 2.1

parameters:
  app-version:
    type: string
    default: 1.0.0

#commands:
#  sayhello:
#    description: "A very simple command for demonstration purposes"
#    parameters:
#      to:
#        type: string
#        default: "Hello World"
#    steps:
#      - run: echo << parameters.to >>

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:11.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:11.0'

orbs:
  maven: circleci/maven@1.4.1
  gh: circleci/github-cli@1.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
          post-steps:
            - run:
                command: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ${<< parameters.app-version >>}
      - build:
          context: SonarCloud
      - gh/release:
#          notes-file: changelog.md
          tag: << parameters.app-version >>
          title: The initial release
          requires:
            - maven/test
          context:
            - GitHub
          filters:
            branches:
              only:
                - master