version: 2.1

orbs:
  gh: circleci/github-cli@2.0

jobs:
  build:
    parameters:
      app-version:
        type: env_var_name
        default: APP_VERSION
    docker:
      - image: 'cimg/openjdk:11.0'
    steps:
      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: mvn verify sonar:sonar
      - run:
          name: Get version
          command: |
            APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo -n $APP_VERSION
            echo 'export APP_VERSION_ENV_VAR='$APP_VERSION >> "$BASH_ENV"
      - run:
          name: Print App Version
          command: |
            echo ${APP_VERSION_ENV_VAR}
      - gh/install
      - run:
          command: |
            echo ${APP_VERSION_ENV_VAR}
            echo ${GITHUB_TOKEN}
            gh release create "${APP_VERSION_ENV_VAR}" --repo "$(git config --get remote.origin.url)"
          name: Create Release

workflows:
  maven_test:
    jobs:
      - build:
          context: GitHub
#      - gh/release:
#          title: The initial release
#          requires:
#            - build
#          tag: 1.3.1
#          context:
#            - GitHub
#          filters:
#            branches:
#              only:
#                - master