version: 2.1

orbs:
  gh: circleci/github-cli@2.0

jobs:
  build:
    parameters:
      app-version:
        type: env_var_name
        default: APP_VERSION
    docker:
      - image: 'cimg/openjdk:11.0'
    steps:
      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: mvn verify sonar:sonar
      - run:
          name: Get version
          command: |
            APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo -n $APP_VERSION
            echo 'export APP_VERSION_ENV_VAR="1.2.3"' >> "$BASH_ENV"
      - gh/install
      - run:
          name: Print App Version
          command: |
            echo ${APP_VERSION_ENV_VAR}

workflows:
  maven_test:
    jobs:
      - build:
          context: SonarCloud